### ISSUE TITLE
Please update the tool

### ISSUE THREAD

**Issue by brice-laurencin** [CleverCloud/testcontainers-ceph#2]
This is an awesome initiative!

But sadly it's not working exactly as expected.
The Ceph version packaged in the tool does not seem to support SSE-C (trying to push a SSE-C crypted file gives an HTTP 400 with `null` exception.)

Trying to update to a later Ceph version (`quay.io/ceph/daemon:latest-quincy`) the `ceph/daemon` it simply does not try (I tried setting a container through `docker-compose` to be able to mimick the config with `testcontainers` but failed so far. The network configuration is a pain to get correctly.
Same with `quay.io/ceph/demon:latest-quincy` (and it needs empty `/var/lib/ceph` and `/etc/ceph`).

Is there a chance you can have a look at this?

**Comment by brice-laurencin** [comment]
Actually, I eventually got it running with
```
    private val ceph = GenericContainer(
        DockerImageName.parse("quay.io/ceph/demo:latest-quincy")
    )
        .withEnv(
            mapOf(
                "CEPH_PUBLIC_NETWORK" to "127.0.0.1/32",
                "MON_IP" to "127.0.0.1",
                "CEPH_DEMO_UID" to "admin",
                "CEPH_DEMO_ACCESS_KEY" to RandomStringUtils.randomAlphanumeric(32),
                "CEPH_DEMO_SECRET_KEY" to RandomStringUtils.randomAlphanumeric(32),
                "RGW_NAME" to "localhost",
            )
        )
        .withExposedPorts(8080)
```

**Comment by brice-laurencin** [comment]
After a few hours fight, here is how I was able to have it working with SSE-C available: 
```GenericContainer(
        DockerImageName.parse("quay.io/ceph/demo:latest-quincy"),
    )
        .withEnv(
            mapOf(
                "CEPH_PUBLIC_NETWORK" to "127.0.0.1/32",
                "MON_IP" to "127.0.0.1",
                "CEPH_DEMO_UID" to "admin",
                "CEPH_DEMO_ACCESS_KEY" to ACCESS_KEY,
                "CEPH_DEMO_SECRET_KEY" to SECRET_KEY,
                "RGW_NAME" to "localhost",
            ),
        )
        .withExposedPorts(CEPH_PORT)
        // This command will update the `demo` script to configure rgw so it accepts sse-c request without SSL.
        .withCreateContainerCmdModifier { it.withEntrypoint(
            "bash", "-c",
            """sed -i '340irgw verify ssl = false\
            rgw crypt require ssl = false' /opt/ceph-container/bin/demo;
            /opt/ceph-container/bin/demo
        """.trimIndent(),
        ) }
        .waitingFor(LogMessageWaitStrategy().withRegEx(".*\"user\": \"admin\",\n").withTimes(2))
        .withStartupTimeout(180.seconds.toJavaDuration())
```

I removed the SSL check so that the Java AWS-SDK could use the S3 service on the container. Otherwise, we would have to setup the certificates for `localhost`.
Here, it just works.

**Comment by jarlah** [comment]
Use this version instead. Its listed in community modules now. https://github.com/jarlah/testcontainers-ceph

**Comment by jarlah** [comment]
@brice-laurencin I have added a PR now that optionally allows to disable ssl checks
https://github.com/jarlah/testcontainers-ceph/pull/6
maybe this will work? at least better than relying on line numbers. And you dont have to maintain it ...

**Comment by brice-laurencin** [comment]
This is awesome, thanks a lot!
maybe add a deprecation warning in the REAMDE for this repo.
I'll switch to the other one once the SSL fix is merged.

Thanks again.

**Comment by jarlah** [comment]
> This is awesome, thanks a lot! maybe add a deprecation warning in the REAMDE for this repo. I'll switch to the other one once the SSL fix is merged.
> 
> Thanks again.

@brice-laurencin I'm not the author of **this** repo, I am basically just providing an alternative and newer version of the same thing in my own repo. I can add an issue here in which I point people to my new repo, but if the author rejects that idea at some point, it might be closed. Understandably.

**Comment by brice-laurencin** [comment]
this issue can serve as a pointer to your working solution, that's already it.
